name: Secret Scanner
description: Scans the code base to detect for the presence of secrets.
inputs:
  github_token:
    required: true
    description: GitHub token for authentication, required for accessing the repository and posting comments.
  gitleaks_license:
    required: true
    description: Gitleaks license key to use the licensed version.

runs:
  using: "composite"
  steps:
    - name: Gitleaks scanning
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITLEAKS_LICENSE: ${{ inputs.gitleaks_license }}

    - name: TruffleHog 🐽 scanning
      uses: trufflesecurity/trufflehog@v3
      with:
        extra_args: --results=verified,unknown
