spring:
  application:
    name: cp-case-document-knowledge-service

  datasource:
    # Override these via env in each environment
    url: ${CP_CDK_DATASOURCE_URL:jdbc:postgresql://localhost:55432/appdb}
    username: ${CP_CDK_DATASOURCE_USERNAME:app}
    password: ${CP_CDK_DATASOURCE_PASSWORD:app}
    hikari:
      pool-name: cp-hikari
      maximum-pool-size: ${CP_CDK_DB_POOL_SIZE:20}
      minimum-idle: ${CP_CDK_DB_MIN_IDLE:5}
      connection-timeout: 30000        # ms
      idle-timeout: 600000             # ms
      max-lifetime: 1800000            # ms
      keepalive-time: 300000           # ms
      validation-timeout: 5000         # ms

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate               # schema managed by Flyway
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.connection.provider_disables_autocommit: true
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true

  sql:
    init:
      mode: never

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}

server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful
  http2:
    enabled: true
  forward-headers-strategy: framework   # honor X-Forwarded-* behind proxies
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: "application/json,application/xml,text/html,text/plain,text/xml,text/css,application/javascript"

management:
  server:
    # Keep actuator on same port by default; override if you want a separate port
    port: ${MANAGEMENT_SERVER_PORT:${SERVER_PORT:8082}}
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info,metrics,prometheus,env,loggers,threaddump"
  endpoint:
    health:
      probes:
        enabled: true                  # liveness/readiness groups
  metrics:
    tags:
      service: example-service
      cluster: ${CLUSTER_NAME:local}
      region: ${REGION:local}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLER_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_TRACES_URL:http://localhost:4318/v1/traces}
    metrics:
      export:
        enabled: ${OTEL_METRICS_ENABLED:false}
        url: ${OTEL_METRICS_URL:http://localhost:4318/v1/metrics}

springdoc:
  api-docs:
    enabled: ${OPENAPI_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}

logging:
  level:
    root: INFO
  # Use your JSON config (async) — make sure this file exists
  config: classpath:logback-spring.xml

# Optional: Java 21 virtual threads (Boot 3.2+ / 4.x)
spring.threads.virtual.enabled: ${VIRTUAL_THREADS:false}
