name: Secrets Scanning Shared Workflow
on:
  workflow_call:
    secrets:
      GITLEAKS_LICENSE:
        required: true
      HMCTS_CP_GITLEAKS_REGEX_INTERNAL_URL:
        required: true
      HMCTS_CP_GITLEAKS_REGEX_SYSTEM_IDS:
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hmcts/secrets-scanner@v1.2
        with:
          github_token: ${{ github.token }}
          gitleaks_license: ${{ secrets.GITLEAKS_LICENSE }}
          run_hmcts_rules: "true"
          hmcts_regex_internal_urls: ${{ secrets.HMCTS_CP_GITLEAKS_REGEX_INTERNAL_URL }}
          hmcts_regex_system_ids: ${{ secrets.HMCTS_CP_GITLEAKS_REGEX_SYSTEM_IDS }}